export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  CURRENT_ROUND_NOT_FOUND: "CURRENT_ROUND_NOT_FOUND",
  LATEST_ROUND_NOT_FOUND: "LATEST_ROUND_NOT_FOUND",
  ROUND_NOT_FOUND: "ROUND_NOT_FOUND",
  CURRENT_BET_NOT_FOUND: "CURRENT_BET_NOT_FOUND",
  BET_NOT_FOUND: "BET_NOT_FOUND",

  ROUND_NOT_ACCEPTING_BETS: "ROUND_NOT_ACCEPTING_BETS",
  DUPLICATED_BET: "DUPLICATED_BET",
  BET_NOT_ACCEPTED: "BET_NOT_ACCEPTED",
  CASHOUT_NOT_ALLOWED: "CASHOUT_NOT_ALLOWED",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
} as const;
