export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_ALREADY_EXISTS: "WALLET_ALREADY_EXISTS",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  DUPLICATED_EVENT: "DUPLICATED_EVENT",
} as const;
