export const ROUND_REPOSITORY = Symbol("ROUND_REPOSITORY");
export const WALLET_EVENTS_PUBLISHER = Symbol("WALLET_EVENTS_PUBLISHER");
export const GAME_REALTIME_NOTIFIER = Symbol("GAME_REALTIME_NOTIFIER");
export const ID_GENERATOR = Symbol("ID_GENERATOR");
export const CLOCK = Symbol("CLOCK");
export const OUTBOX_REPOSITORY = Symbol("OUTBOX_REPOSITORY");
export const GAME_UNIT_OF_WORK = Symbol("GAME_UNIT_OF_WORK");
export const PROCESSED_EVENT_REPOSITORY = Symbol("PROCESSED_EVENT_REPOSITORY");
